### ISSUE TITLE
Renaming the Repo or Arduino Library

### ISSUE THREAD

**Issue by badfishblues** [EmotiBit/EmotiBit_FeatherWing#40]
Arduino generally recognizes the library.properties in the folder and registers that version as installed, in the library manager. This behavior was designed to also allow for importing libraries from zip or direct download without the manager. 

**Edge Case 1:** If they have different folder names and you already have an unreleased version from git, the manager downloads and creates a new folder, without changing the old one. Could lead to ugly conflicts.

**Edge Case 2:** If they have different folder names and you have a released version from git, it is visible as installed in the library manager, and updating the version results in Arduino erasing everything in the git repo except for an empty examples folder, and creating a new library folder with that version and name. No potential for direct file conflicts

**Edge Case 3:**  If they have the same folder name, and you already have an unreleased version from git, arduino will create a new folder according to the convention _arduino_123456_, which leaves your git repo untouched, but could lead to ugly conflicts for external sketches.

**Edge Case 4:** If they have the same folder name and you already have a released version from git, and you use the library manager to switch to a different version, Arduino deletes your repo and creates a new folder according to the convention _arduino_123456_, which doesn't lead to code conflicts, but is not user friendly.

**Edge Case 5:** If they have the same folder name and library was initially downloaded by the Library manager, git won't allow you to clone into the libraries folder. This cannot lead to any conflicts that I can think of.

_**Furthermore:**_
  - Convention used by adafruit for NeoPixel is same name, but not CharliePlex
      - Adafruit_Neopixel
      - Adafruit_IS31FL3731_Library vs Adafruit_IS31FL3731
- Changing an Arduino Library name is less simple than the git name:
   - https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ#how-can-i-change-my-librarys-name

**Comment by nitin710** [comment]
### Fix:
- Name the Github repo with a name that you want the library to be downloaded as in `/Documents/ARduino/Libraries`. Ex: `EmotiBit_MAX30101` should have the github repo name `EmotiBit_MAX30101` .
  - Arduino interprest `_` as a `<space>`, so the library appears as `EmotiBit MAX30101` in the Arduino interface.
  - This also ensures that if, a library has been installed from arduino library manager, it cannot be overwritten using git clone.
  - If a library was cloned from github, then it updates the Arduino library manager automatically, and the latest pull is reflected in the arduino interface.
